/-
Copyright 2025 The Formal Conjectures Authors.
Copyright 2026 The mathdb-lean Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import MathDBUtil

/-!
Converted from another corpus. `source` names it, `source_version`
pins the revision, and `source_locator` points at the one
declaration this came from. Every `source_` field describes that
declaration as it stands there, not as it stands here.

Read `track` for whether the problem is solved, which is a fact
about mathematics. `source_has_lean_proof` is a different claim --
whether that corpus holds a machine-checked proof -- and is false
for almost every problem, because it is a statement repository.

- problem_id: E433
- collection: erdos
- question_id: erdos:433
- source: formal-conjectures
- source_locator: FormalConjectures/ErdosProblems/433.lean#erdos_433
- source_version: e04cc601840dd7a37f89b821a67f3a9e3c38d9c3
- prose: For every fixed $k \geq 2$, Erdős and Graham conjectured that $$g(k,n) \sim \frac{n^2}{k-1}.$$ The conjecture was proved by Dixmier [Di90].
- notes: Erdos Problem 433 -- https://www.erdosproblems.com/433
- track: solved
- answer_shape: decide
- source_stem: 433
- mathdb_ref: erdos:433
- source_namespace: Erdos433
- source_theorem: erdos_433
- source_category: research solved
- source_ams: 11
- source_has_lean_proof: false
- source_lean_proof_kernel_clean: n/a
- generator: adapters/formal_conjectures/adapter.py
- gold_answer: True
-/

namespace Problem

open Filter
open scoped Topology

/-- The Frobenius number of a finite set $A$: the greatest natural number outside the
additive submonoid generated by $A$. -/
noncomputable def frobeniusNumber (A : Finset ℕ) : ℕ :=
  sSup {m | m ∉ AddSubmonoid.closure (A : Set ℕ)}

/-- The largest Frobenius number of a $k$-element subset of $\{1,\ldots,n\}$ whose
elements have greatest common divisor one. -/
noncomputable def g (k n : ℕ) : ℕ :=
  sSup {m | ∃ A : Finset ℕ, A ⊆ Finset.Icc 1 n ∧ A.card = k ∧ A.gcd id = 1 ∧
    m = frobeniusNumber A}

abbrev Target (verdict : Prop) : Prop :=
    verdict ↔ ∀ k, 2 ≤ k →
        Tendsto (fun n : ℕ => (g k n : ℝ) / ((n : ℝ) ^ 2 / ((k : ℝ) - 1))) atTop (𝓝 1)

end Problem
