/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module  -- shake: keep-all --deprecated_module: ignore

public import MathDBMathlib.Algebra.GCDMonoid.Finset
public import MathDBMathlib.Algebra.GradedMonoid
public import MathDBMathlib.Algebra.Group.Action.Pointwise.Set.Basic
public import MathDBMathlib.Algebra.Group.GrowthFunction
public import MathDBMathlib.Algebra.Group.Indicator
public import MathDBMathlib.Algebra.Homology.DerivedCategory.Ext.GradedAlgebra
public import MathDBMathlib.Algebra.MvPolynomial.PoissonBracket
public import MathDBMathlib.Algebra.MvPolynomial.RegularFunction
public import MathDBMathlib.Algebra.Order.Group.Pointwise.Interval
public import MathDBMathlib.Algebra.Polynomial.Algebra
public import MathDBMathlib.Algebra.Polynomial.Basic
public import MathDBMathlib.Algebra.Polynomial.HasseDeriv
public import MathDBMathlib.Algebra.Powerfree
public import MathDBMathlib.Algebra.QuadraticAlgebra.Instances
public import MathDBMathlib.Algebra.Ring.PythagorasNumber
public import MathDBMathlib.AlgebraicGeometry.EllipticCurve.GlobalPeriod
public import MathDBMathlib.AlgebraicGeometry.EllipticCurve.MinimalDiscriminant
public import MathDBMathlib.AlgebraicGeometry.EllipticCurve.Regulator
public import MathDBMathlib.AlgebraicGeometry.EllipticCurve.Tamagawa
public import MathDBMathlib.AlgebraicGeometry.ProjectiveSpace
public import MathDBMathlib.AlgebraicGeometry.VectorBundle
public import MathDBMathlib.Analysis.Asymptotics.Basic
public import MathDBMathlib.Analysis.Equidistribution.ModOne
public import MathDBMathlib.Analysis.Fourier.SpectralSets
public import MathDBMathlib.Analysis.HasGaps
public import MathDBMathlib.Analysis.Matrix.Spectrum
public import MathDBMathlib.Analysis.Real.Cardinality
public import MathDBMathlib.Analysis.SpecialFunctions.AdditiveCharacter
public import MathDBMathlib.Analysis.SpecialFunctions.Log.Basic
public import MathDBMathlib.Analysis.SpecialFunctions.NthRoot
public import MathDBMathlib.Combinatorics.AP.Basic
public import MathDBMathlib.Combinatorics.Additive.Basis
public import MathDBMathlib.Combinatorics.Additive.Convolution
public import MathDBMathlib.Combinatorics.Additive.Coset
public import MathDBMathlib.Combinatorics.Additive.DifferenceBasis
public import MathDBMathlib.Combinatorics.Additive.RestrictedSumset
public import MathDBMathlib.Combinatorics.Additive.VCDim
public import MathDBMathlib.Combinatorics.Basic
public import MathDBMathlib.Combinatorics.Digraph.Tournament
public import MathDBMathlib.Combinatorics.Hypergraph.ThreeUniform
public import MathDBMathlib.Combinatorics.LatinSquare
public import MathDBMathlib.Combinatorics.LimitObjects.Graphon
public import MathDBMathlib.Combinatorics.LimitObjects.Tournamenton
public import MathDBMathlib.Combinatorics.Ramsey
public import MathDBMathlib.Combinatorics.Ramsey.Diagonal
public import MathDBMathlib.Combinatorics.SetFamily.PropertyB
public import MathDBMathlib.Combinatorics.SetFamily.Sunflower
public import MathDBMathlib.Combinatorics.SetFamily.UnionFree
public import MathDBMathlib.Combinatorics.SetFamily.VCDim
public import MathDBMathlib.Combinatorics.SetTheory.PartitionRelation
public import MathDBMathlib.Combinatorics.SimpleGraph.AnnihilationNumber
public import MathDBMathlib.Combinatorics.SimpleGraph.Balanced
public import MathDBMathlib.Combinatorics.SimpleGraph.Circumference
public import MathDBMathlib.Combinatorics.SimpleGraph.Clique
public import MathDBMathlib.Combinatorics.SimpleGraph.Coloring.Vertex
public import MathDBMathlib.Combinatorics.SimpleGraph.CompleteGraphEdgeCount
public import MathDBMathlib.Combinatorics.SimpleGraph.Connectivity
public import MathDBMathlib.Combinatorics.SimpleGraph.Cvetkovic
public import MathDBMathlib.Combinatorics.SimpleGraph.Cycle
public import MathDBMathlib.Combinatorics.SimpleGraph.CycleRank
public import MathDBMathlib.Combinatorics.SimpleGraph.Decomposition
public import MathDBMathlib.Combinatorics.SimpleGraph.Degeneracy
public import MathDBMathlib.Combinatorics.SimpleGraph.Degrees
public import MathDBMathlib.Combinatorics.SimpleGraph.DiamExtra
public import MathDBMathlib.Combinatorics.SimpleGraph.Domination
public import MathDBMathlib.Combinatorics.SimpleGraph.Eccentricity
public import MathDBMathlib.Combinatorics.SimpleGraph.EdgeColouring
public import MathDBMathlib.Combinatorics.SimpleGraph.FractionalAlpha
public import MathDBMathlib.Combinatorics.SimpleGraph.HarmonicIndex
public import MathDBMathlib.Combinatorics.SimpleGraph.HomDensity
public import MathDBMathlib.Combinatorics.SimpleGraph.Hypercube
public import MathDBMathlib.Combinatorics.SimpleGraph.Independence
public import MathDBMathlib.Combinatorics.SimpleGraph.Induced
public import MathDBMathlib.Combinatorics.SimpleGraph.InducedTreeNeighborhood
public import MathDBMathlib.Combinatorics.SimpleGraph.Johnson
public import MathDBMathlib.Combinatorics.SimpleGraph.LargestInducedTree
public import MathDBMathlib.Combinatorics.SimpleGraph.LovaszTheta
public import MathDBMathlib.Combinatorics.SimpleGraph.Matching
public import MathDBMathlib.Combinatorics.SimpleGraph.PathCover
public import MathDBMathlib.Combinatorics.SimpleGraph.Prod
public import MathDBMathlib.Combinatorics.SimpleGraph.QuasiLineGraph
public import MathDBMathlib.Combinatorics.SimpleGraph.Ramsey
public import MathDBMathlib.Combinatorics.SimpleGraph.Residue
public import MathDBMathlib.Combinatorics.SimpleGraph.Saturation
public import MathDBMathlib.Combinatorics.SimpleGraph.SizeRamsey
public import MathDBMathlib.Combinatorics.SimpleGraph.SpanningTree
public import MathDBMathlib.Combinatorics.SimpleGraph.SubgraphIsomorphism
public import MathDBMathlib.Combinatorics.SimpleGraph.SzegedIndex
public import MathDBMathlib.Combinatorics.SimpleGraph.Temperature
public import MathDBMathlib.Combinatorics.SimpleGraph.UnitDistancePlaneGraph
public import MathDBMathlib.Combinatorics.SimpleGraph.VertexDistance
public import MathDBMathlib.Combinatorics.SimpleGraph.WellTotallyDominated
public import MathDBMathlib.Combinatorics.SimpleGraph.WienerIndex
public import MathDBMathlib.Combinatorics.YoungDiagram
public import MathDBMathlib.Computability.AutomaticSequence
public import MathDBMathlib.Computability.BitstringEncoding
public import MathDBMathlib.Computability.Complexity
public import MathDBMathlib.Computability.DFA
public import MathDBMathlib.Computability.Primrec
public import MathDBMathlib.Computability.TuringMachine.BusyBeavers
public import MathDBMathlib.Computability.TuringMachine.Notation
public import MathDBMathlib.Computability.TuringMachine.PostTuringMachine
public import MathDBMathlib.Data.Bool.Basic
public import MathDBMathlib.Data.Finset.Card
public import MathDBMathlib.Data.Finset.Powerset
public import MathDBMathlib.Data.Finset.ReciprocalSum
public import MathDBMathlib.Data.Int.IntermediateValue
public import MathDBMathlib.Data.Int.Order.Basic
public import MathDBMathlib.Data.Nat.Factorization.Basic
public import MathDBMathlib.Data.Nat.Full
public import MathDBMathlib.Data.Nat.Init
public import MathDBMathlib.Data.Nat.MaxPrimeFac
public import MathDBMathlib.Data.Nat.PerfectPower
public import MathDBMathlib.Data.Nat.Prime.Composite
public import MathDBMathlib.Data.Nat.Prime.Defs
public import MathDBMathlib.Data.Nat.Prime.Finset
public import MathDBMathlib.Data.Nat.Prime.Infinite
public import MathDBMathlib.Data.Nat.Squarefree
public import MathDBMathlib.Data.Real.Constants
public import MathDBMathlib.Data.Real.NearestInt
public import MathDBMathlib.Data.Set.Density
public import MathDBMathlib.Data.Set.Interval
public import MathDBMathlib.Data.Set.Triplewise
public import MathDBMathlib.Data.Sym.Sym2
public import MathDBMathlib.Data.ZMod.Fp
public import MathDBMathlib.Data.ZMod.PerfectDifferenceSet
public import MathDBMathlib.Dynamics.SymbolicDynamics.BlockComplexity
public import MathDBMathlib.FieldTheory.MilnorKTheory
public import MathDBMathlib.FieldTheory.MvRatFunc.Defs
public import MathDBMathlib.Geometry.Euclidean
public import MathDBMathlib.Geometry.Manifold.LieGroupPresentation
public import MathDBMathlib.Geometry.Metric
public import MathDBMathlib.Geometry.«2d»
public import MathDBMathlib.Geometry.«3d»
public import MathDBMathlib.GroupTheory.Torsion
public import MathDBMathlib.Lean.Elab.InfoTree.Util
public import MathDBMathlib.LinearAlgebra.AffineSpace.Simplex.Basic
public import MathDBMathlib.LinearAlgebra.GeneralLinearGroup
public import MathDBMathlib.LinearAlgebra.QuadraticForm.UInvariant
public import MathDBMathlib.LinearAlgebra.SpecialLinearGroup
public import MathDBMathlib.Logic.Equiv.Fin.Rotate
public import MathDBMathlib.ModelTheory.Decidability
public import MathDBMathlib.ModelTheory.Encoding
public import MathDBMathlib.ModelTheory.Real
public import MathDBMathlib.NumberTheory.AdditionChain
public import MathDBMathlib.NumberTheory.AdditiveComplement
public import MathDBMathlib.NumberTheory.AdditivelyComplete
public import MathDBMathlib.NumberTheory.AlmostPrime
public import MathDBMathlib.NumberTheory.Amicable
public import MathDBMathlib.NumberTheory.AutomaticNumber
public import MathDBMathlib.NumberTheory.AutomorphicForm.BorelJacquet
public import MathDBMathlib.NumberTheory.AutomorphicForm.BorelJacquet.CenterAction
public import MathDBMathlib.NumberTheory.AutomorphicForm.BorelJacquet.LieDeriv
public import MathDBMathlib.NumberTheory.AutomorphicForm.BorelJacquet.Subgroups
public import MathDBMathlib.NumberTheory.BeurlingPrimes
public import MathDBMathlib.NumberTheory.Carmichael
public import MathDBMathlib.NumberTheory.CoveringSystem
public import MathDBMathlib.NumberTheory.DiophantineApproximation.ZNumber
public import MathDBMathlib.NumberTheory.DirichletCharacter.Basic
public import MathDBMathlib.NumberTheory.Divisors
public import MathDBMathlib.NumberTheory.ExpansionEntropy
public import MathDBMathlib.NumberTheory.Harmonic
public import MathDBMathlib.NumberTheory.Lacunary
public import MathDBMathlib.NumberTheory.LegendreSymbol.Basic
public import MathDBMathlib.NumberTheory.MultiplicativelyIndependent
public import MathDBMathlib.NumberTheory.NormalNumber
public import MathDBMathlib.NumberTheory.NumberField.FundamentalDiscriminant
public import MathDBMathlib.NumberTheory.NumberField.Quadratic
public import MathDBMathlib.NumberTheory.PisotNumber
public import MathDBMathlib.NumberTheory.PracticalNumbers
public import MathDBMathlib.NumberTheory.PrimeGap
public import MathDBMathlib.NumberTheory.Primitive
public import MathDBMathlib.NumberTheory.SierpinskiNumber
public import MathDBMathlib.NumberTheory.SmoothScale
public import MathDBMathlib.NumberTheory.WallSunSunPrimes
public import MathDBMathlib.NumberTheory.WieferichPrime
public import MathDBMathlib.Order.Bounds.Basic
public import MathDBMathlib.Order.Filter.Cofinite
public import MathDBMathlib.Order.Filter.atTopBot.Finset
public import MathDBMathlib.Order.Interval.Finset.Basic
public import MathDBMathlib.Order.Interval.Finset.Nat
public import MathDBMathlib.Order.Nat
public import MathDBMathlib.Order.Unimodular
public import MathDBMathlib.Probability.FiniteMethod
public import MathDBMathlib.RingTheory.Bialgebra.Cohomology
public import MathDBMathlib.RingTheory.Bialgebra.TrivialModule
public import MathDBMathlib.RingTheory.CohenMacaulayModule
public import MathDBMathlib.RingTheory.Ideal.Basic
public import MathDBMathlib.RingTheory.Ideal.Defs
public import MathDBMathlib.RingTheory.Ideal.Maximal
public import MathDBMathlib.RingTheory.IntersectionMultiplicity
public import MathDBMathlib.RingTheory.MvPolynomial.LexPlusPowers
public import MathDBMathlib.RingTheory.Noetherian.Defs
public import MathDBMathlib.RingTheory.SystemOfParameters
public import MathDBMathlib.RingTheory.Valuation.LocalUniformization
public import MathDBMathlib.SetTheory.Cardinal.Arithmetic
public import MathDBMathlib.SetTheory.Cardinal.Continuum
public import MathDBMathlib.SetTheory.Cardinal.SimpleGraph
public import MathDBMathlib.Tactic.Linter.Term
public import MathDBMathlib.Topology.AbsoluteNeighborhoodRetract
public import MathDBMathlib.Topology.Algebra.InfiniteSum.Group
public import MathDBMathlib.Topology.Algebra.InfiniteSum.Order
public import MathDBMathlib.Topology.Algebra.InfiniteSum.Real
public import MathDBMathlib.Topology.CardinalInvariants
public import MathDBMathlib.Topology.Discrete
public import MathDBMathlib.Topology.GDelta
public import MathDBMathlib.Topology.Homogeneous
public import MathDBMathlib.Topology.LebesgueCoveringDimension
public import MathDBMathlib.Topology.MetricSpace.MetricSeparated
