/-
Copyright 2025 The Formal Conjectures Authors.
Copyright 2026 The mathdb-lean Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import MathDBUtil

/-!
Converted from another corpus. `source` names it, `source_version`
pins the revision, and `source_locator` points at the one
declaration this came from. Every `source_` field describes that
declaration as it stands there, not as it stands here.

Read `track` for whether the problem is solved, which is a fact
about mathematics. `source_has_lean_proof` is a different claim --
whether that corpus holds a machine-checked proof -- and is false
for almost every problem, because it is a statement repository.

- problem_id: NAndrewsCurtis_andrews_curtis_conjecture
- collection: wikipedia
- question_id: wikipedia:AndrewsCurtis
- source: formal-conjectures
- source_locator: FormalConjectures/Wikipedia/AndrewsCurtis.lean#andrews_curtis_conjecture
- source_version: e04cc601840dd7a37f89b821a67f3a9e3c38d9c3
- prose: **The Andrews-Curtis conjecture.** Every normally generating `n`-tuple in the free group of rank `n` is Andrews-Curtis equivalent to the standard tuple of free generators.
- notes: Wikipedia: AndrewsCurtis -- https://en.wikipedia.org/wiki/Andrews%E2%80%93Curtis_conjecture
- track: open
- answer_shape: proof
- source_stem: AndrewsCurtis
- source_namespace: AndrewsCurtis
- source_theorem: andrews_curtis_conjecture
- source_category: research open
- source_ams: 20
- source_has_lean_proof: false
- source_lean_proof_kernel_clean: n/a
- generator: adapters/formal_conjectures/adapter.py
-/

namespace Problem

/-- An `n`-tuple of relators in the free group on `n` generators. -/
abbrev RelatorTuple (n : ℕ) := Fin n → FreeGroup (Fin n)

/-- The standard relator tuple, consisting of the free generators themselves. -/
def standardRelators (n : ℕ) : RelatorTuple n :=
  fun i ↦ FreeGroup.of i

/--
The elementary Andrews-Curtis moves: inversion or multiplication of relators,
interchange of two relators, and conjugation of one relator by an arbitrary word.
-/
inductive Move {n : ℕ} : RelatorTuple n → RelatorTuple n → Prop
  | invert (r : RelatorTuple n) (i : Fin n) :
      Move r (Function.update r i (r i)⁻¹)
  | multiply (r : RelatorTuple n) (i j : Fin n) (hij : i ≠ j) :
      Move r (Function.update r i (r i * r j))
  | swap (r : RelatorTuple n) (i j : Fin n) :
      Move r (fun k ↦ r (Equiv.swap i j k))
  | conjugate (r : RelatorTuple n) (i : Fin n) (w : FreeGroup (Fin n)) :
      Move r (Function.update r i (w * r i * w⁻¹))

/-- Andrews-Curtis equivalence is the equivalence relation generated by elementary moves. -/
def Equivalent {n : ℕ} : RelatorTuple n → RelatorTuple n → Prop :=
  Relation.EqvGen Move

/--
A relator tuple normally generates the free group when the normal closure of its
range is the whole free group. Equivalently, the associated balanced presentation
presents the trivial group.
-/
def NormallyGenerates {n : ℕ} (r : RelatorTuple n) : Prop :=
  Subgroup.normalClosure (Set.range r) = ⊤

abbrev Target : Prop :=
    ∀ (n : ℕ) (r : RelatorTuple n)
        (hr : NormallyGenerates r),
      Equivalent r (standardRelators n)

end Problem
