/-
Copyright 2025 The Formal Conjectures Authors.
Copyright 2026 The mathdb-lean Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import MathdbUtil

/-!
Converted from another corpus. `source` names it, `source_version`
pins the revision, and `source_locator` points at the one
declaration this came from. Every `source_` field describes that
declaration as it stands there, not as it stands here.

Read `track` for whether the problem is solved, which is a fact
about mathematics. `source_has_lean_proof` is a different claim --
whether that corpus holds a machine-checked proof -- and is false
for almost every problem, because it is a statement repository.

- problem_id: O109845_conjecture
- collection: oeis
- question_id: oeis:109845
- source: formal-conjectures
- source_locator: FormalConjectures/OEIS/109845.lean#conjecture
- source_version: e04cc601840dd7a37f89b821a67f3a9e3c38d9c3
- prose: Conjecture: There are infinitely many primes in this sequence.
- notes: OEIS A109845 -- https://oeis.org/A109845
- track: open
- answer_shape: proof
- source_stem: 109845
- source_namespace: OeisA109845
- source_theorem: conjecture
- source_category: research open
- source_ams: 11
- source_has_lean_proof: false
- source_lean_proof_kernel_clean: n/a
- context_lemmas: a_0 a_1 a_2 a_3 a_4
- generator: adapters/formal_conjectures/adapter.py
-/

namespace Problem

/--
$a(1) = 2$; $a(2n)$ = lcm of all previous terms + 1; $a(2n+1)$ = lcm of all previous terms - 1.
The sequence is correctly generated by the recurrence relation $a(1)=2$, $a(2)=3$,
and for $n \ge 3$:
$$a(n) = a(n-1)^2 + (-1)^n a(n-1) + (-1)^n.$$
We use $0$-based indexing here, so $a(n)$ corresponds to the OEIS sequence $a(n+1)$.
-/
def a : ℕ → ℕ
  | 0 => 2
  | 1 => 3
  | n + 2 =>
    let prev := a (n + 1)
    if n % 2 = 0 then
      prev * prev - (prev + 1)
    else
      prev * prev + prev + 1

/-! Auxiliary lemmas upstream proves in the same file, frozen in with
the definitions: an answer may cite them or prove its own. Each is
tagged `API` or `test` upstream and is listed in `context_lemmas`
above. See docs/CONVERSION.md for what is deliberately not here. -/

@[category test, AMS 11]
theorem a_0 : a 0 = 2 := by rfl

@[category test, AMS 11]
theorem a_1 : a 1 = 3 := by rfl

@[category test, AMS 11]
theorem a_2 : a 2 = 5 := by rfl

@[category test, AMS 11]
theorem a_3 : a 3 = 31 := by rfl

@[category test, AMS 11]
theorem a_4 : a 4 = 929 := by rfl

abbrev Target : Prop :=
    Set.Infinite {n : ℕ | (a n).Prime}

end Problem
