/-
Copyright 2025 The Formal Conjectures Authors.
Copyright 2026 The mathdb-lean Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import MathdbUtil

/-!
Converted from another corpus. `source` names it, `source_version`
pins the revision, and `source_locator` points at the one
declaration this came from. Every `source_` field describes that
declaration as it stands there, not as it stands here.

Read `track` for whether the problem is solved, which is a fact
about mathematics. `source_has_lean_proof` is a different claim --
whether that corpus holds a machine-checked proof -- and is false
for almost every problem, because it is a statement repository.

- problem_id: O105210_conjecture
- collection: oeis
- question_id: oeis:105210
- source: formal-conjectures
- source_locator: FormalConjectures/OEIS/105210.lean#conjecture
- source_version: e04cc601840dd7a37f89b821a67f3a9e3c38d9c3
- prose: This suggests that there may be infinitely many different (non-merging) sequences obtained by choosing different starting values.
- notes: OEIS A105210 -- https://oeis.org/A105210
- track: open
- answer_shape: proof
- source_stem: 105210
- source_namespace: OeisA105210
- source_theorem: conjecture
- source_category: research open
- source_ams: 11
- source_has_lean_proof: false
- source_lean_proof_kernel_clean: n/a
- generator: adapters/formal_conjectures/adapter.py
-/

namespace Problem

open Nat Finset

/-- The sum of distinct prime factors of $n$ that are strictly less than $n$. -/
def sumRelevantPrimeFactors (n : ℕ) : ℕ :=
  (Nat.primeFactors n).sum (fun p => if p < n then p else 0)

/-- The primary defining sequence `a`.
$a(1) = 393$; for $n > 1$, $a(n)$ = $a(n-1)$ + 1 + sum of distinct prime factors of $a(n-1)$
that are < $a(n-1)$. -/
def a : ℕ → ℕ
| 0 => 0
| 1 => 393
| n + 2 =>
  let aPrev := a (n + 1)
  aPrev + 1 + sumRelevantPrimeFactors aPrev
termination_by n => n

/-- The transition function for these sequences: $f(n) = n + 1 + S(n)$. -/
def nextTermFn (n : ℕ) : ℕ :=
  n + 1 + sumRelevantPrimeFactors n

/-- The sequence starting at positive integer $k$, where seq $k$ $n$ is the $n$-th term (1-indexed).
  This is the general form of the sequence A105210 for a starting value $k$. -/
def sequenceStartingAt (k : ℕ) : ℕ → ℕ
| 0 => 0
| 1 => k
| n + 1 => nextTermFn (sequenceStartingAt k n)
termination_by n => n

/-- The set of all terms generated by the sequence starting at $k$. -/
def sequenceSet (k : ℕ) : Set ℕ :=
  { m | ∃ n : ℕ, 1 ≤ n ∧ sequenceStartingAt k n = m }

abbrev Target : Prop :=
    ∃ K : Set ℕ,
      Set.Infinite K ∧
      (∀ k ∈ K, 1 ≤ k) ∧
      (∀ j k : ℕ,
        j ∈ K → k ∈ K → j ≠ k →
        sequenceSet j ∩ sequenceSet k = ∅)

end Problem
